name: burlangapp_v2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  burlang_v2_core:
    path: packages/burlang_v2_core
  burlang_v2_data:
    path: packages/burlang_v2_data
  burlang_v2_domain:
    path: packages/burlang_v2_domain

flutter:
  uses-material-design: true
